### PR TITLE
Initial try for the preprocessing step.

### PR DESCRIPTION
**Pull request by SeguinBe**
Hey,

(mainly intended at @arunbalajeev @isinsukatircioglu and Ashish whose Github Id is unknown to me...)

So i was looking on to processing images, and after ruling out the Java base library (not powerful enough) I managed to have OpenCV working (at least on local for now).

Using the SparkContext.binaryFiles function that give handles to different binary files data, I did not even have to fiddle with Hadoop Input Format (for now...). And I tried to go in the direction we were talking so that our image representation can be compressed/uncompressed in case it has to fly over the network.

About that last point though I'm not sure the current version would totally work, even if ImageData implements Serializable I don't think OpenCV Mat class (coming from the JNI) is Serializable itself. So if things get written to disk and reread at some point, I'm not sure it would work, we may need to write writeObject() and readObject() ourselves. This need further investigation.

Anyway guys, have a look and tell me what you think.

Cheers
Benoit

### CODE REVIEW

**Comment by arvanito** [comment]
Hi Benoit,

can you give a bit more info on what packages you compiled and how on your MAC for java support of OpenCV? 
Also, I see in line 24 that you use lambda expressions. The problem is that in the cluster we do not have Java8 support, 
so we need to avoid them. Can you also comment the code a bit more so that other people have a more clear idea 
of what is going on inside?

I see that the project starts moving nicely :)

Thanks!
Nikos

**Comment by SeguinBe** [comment]
Hi,

About OpenCV I basically followed this http://docs.opencv.org/doc/tutorials/introduction/desktop_java/java_dev_intro.html.
In short the command are (assuming `cmake` and `ant` are installed) :
- `git clone git://github.com/Itseez/opencv.git`
- `mkdir opencv-build`
- `cd opencv-build/`
- `cmake -DBUILD_SHARED_LIBS=OFF -G "Unix Makefiles" ../opencv`
- `ccmake .` If you want to disable some things like tests or perf evals. The video module usually cause some problems on Mac as well.
- `make -j8` to parallelize making process with 8 threads.

You should have the `jar` as something like `opencv-build/bin/opencv-2411.jar`and the JNI library in `opencv-build/lib`.

But for Mac maybe it's easier to just use brew : `brew install opencv --with-java` or Macports `sudo port install opencv +java`.

Damn I had no idea we were not getting lambda expression.... You sure you wanna go with Java and not Scala? :-P

For the comments, yeah I plan on adding them, just wanted to put that visible before going to bed so that people could look at it as soon as possible.

Cheers
Benoit

**Comment by SeguinBe** [comment]
Did the necessary modifications, so that I can let it rest for some time for people to catch up with installation process if necessary. Will merge the pull request when I get more feedback.

Have a good weekend.

**Comment by arvanito** [comment]
Cool, thanks.

**Pull request merged**
